baseURL: "https://dumalabs.uk/"
title: DumaLabs
paginate: 5
theme: "PaperModX"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true  

minify:
  minifyOutput: true

params:
  env: production
  title: "Duma Labs"
  description: "My personal portfolio, and blog."
  keywords: [Blog, Portfolio, Projects, Cyber Security]
  author: Emma
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  showReadingTime: true
  showShareButton: false
  showPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Duma Labs"

  profileMode:
    enabled: true # needs to be explicitly set
    title: "Emma du Maurier"
    subtitle: "My personal portfolio and blog"
    buttons:
      - name: Blog
        url: blog
      - name: About Me
        url: about

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

#   socialIcons:
#    - name: x
#      url: "https://x.com/"
#    - name: stackoverflow
#      url: "https://stackoverflow.com"
#    - name: github
#      url: "https://github.com/"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20    
#    - identifier: cybersecurity
#      name: CyberSecurity
#      url: /cybersecurity/
#      weight: 30
    - identifier: techwhiskers
      name: TechWhiskers
      url: https://blog.techwhiskers.com
      weight: 40

markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
