baseURL = "https://dumalabs.uk/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Duma Labs"
theme = "gokarna"
enableRobotsTXT = true
capitalizelisttitles = true
pluralizelisttitles = false

[params]
  environment = 'production'

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog-posts/"
    weight = 2
  [[menu.main]]
    name = "Cyber Security"
    url = "/cybersecurity/"
    weight = 3



