baseURL = 'http://localhost:1313/'
languageCode = 'en-uk'
title = 'Duma Labs'
theme = 'duma_theme'
relativeURLS = true
enableRobotsTXT = true
pluralizelisttitles = false

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "TTRPG"
    url = "/ttrpg/"
    weight = 30
  [[menu.main]]
    name = "Cybersecurity"
    # IMPORTANT: No 'url' here for the parent dropdown item
    weight = 40
    identifier = "cybersecurity"
  [[menu.main]]
    name = "Photography"
    url = "/photography/"
    weight = 50

  [[menu.main]] # This is the child item for Cybersecurity
    name = "Write-Ups"
    url = "/cybersecurity/writeups/"
    parent = "cybersecurity" # This connects it to the "Cybersecurity" parent
    weight = 10 # Weight within its own dropdown
